// tools/canon-ide/ide.js
// Canon IDE — pure ESM, no build. Mounts into #ide-root.
//
// Responsibilities:
//   - Hold the editable canon state (single source of truth).
//   - Render the 12-tick clock SVG (ticks + chords + focus).
//   - Handle mouse + keyboard editing.
//   - Validate against the shared rules (export refuses if invalid).
//   - Export as a drop-in JS module compatible with logo-glyph.GLYPHS.
//
// Audio preview is best-effort: it pings cosmos-audio if loaded, else a
// short beep via WebAudio. The IDE never depends on cosmos-audio.

import { TEMPLATES, TEMPLATE_IDS, getTemplate, blankCanon } from './templates.js';

// -- shared validation -----------------------------------------------------

export const COLORS = ['R', 'G', 'B', 'C', 'M', 'Y'];
export const COLOR_SET = new Set(COLORS);

const ID_RX = /^[a-z][a-z0-9_]{0,39}$/;

export function validate(canon) {
  const errs = [];
  if (!canon || typeof canon !== 'object') {
    return ['canon must be an object'];
  }
  if (!ID_RX.test(String(canon.canon || ''))) {
    errs.push('id must match [a-z][a-z0-9_]* (1..40)');
  }
  if (canon.direction !== 'cw' && canon.direction !== 'ccw') {
    errs.push('direction must be cw|ccw');
  }
  if (typeof canon.doubleRing !== 'boolean') {
    errs.push('doubleRing must be boolean');
  }
  if (!Array.isArray(canon.ticks) || canon.ticks.length > 12) {
    errs.push('ticks must be an array of length 0..12');
  } else {
    const seen = new Set();
    for (const t of canon.ticks) {
      if (!Number.isInteger(t.tick) || t.tick < 0 || t.tick > 11) {
        errs.push('tick index must be integer 0..11');
      }
      if (t.color !== null && !COLOR_SET.has(t.color)) {
        errs.push('tick color must be RGBCMY or null');
      }
      if (seen.has(t.tick)) errs.push('duplicate tick at ' + t.tick);
      seen.add(t.tick);
    }
  }
  if (!Array.isArray(canon.strings)) {
    errs.push('strings must be an array');
  } else {
    for (const s of canon.strings) {
      if (!Number.isInteger(s.from) || s.from < 0 || s.from > 11) errs.push('string.from invalid');
      if (!Number.isInteger(s.to) || s.to < 0 || s.to > 11) errs.push('string.to invalid');
      if (s.from === s.to) errs.push('string.from === string.to');
      if (s.color !== null && !COLOR_SET.has(s.color)) errs.push('string color invalid');
      if (typeof s.arc !== 'boolean') errs.push('string.arc must be boolean');
    }
  }
  if (!Number.isInteger(canon.phaseAdvance) || canon.phaseAdvance < -6 || canon.phaseAdvance > 6) {
    errs.push('phaseAdvance must be integer in [-6, 6]');
  }
  const isSilence = canon.canon === 'silence';
  if (!isSilence && canon.ticks.length === 0 && canon.strings.length === 0) {
    errs.push('canon must have ≥1 tick or string (except `silence`)');
  }
  return errs;
}

// -- export ---------------------------------------------------------------

export function exportSource(canon) {
  const lines = [];
  lines.push('// Generated by canon-ide @ ' + new Date().toISOString());
  lines.push('// Drop-in compatible with logo-glyph.GLYPHS[<canon>].');
  lines.push('');
  lines.push('export const glyph = {');
  lines.push('  canon: ' + JSON.stringify(canon.canon) + ',');
  lines.push('  direction: ' + JSON.stringify(canon.direction) + ',');
  lines.push('  doubleRing: ' + (canon.doubleRing ? 'true' : 'false') + ',');
  lines.push('  ticks: [');
  for (const t of canon.ticks) {
    lines.push('    { tick: ' + t.tick + ', color: ' + JSON.stringify(t.color) + ' },');
  }
  lines.push('  ],');
  lines.push('  strings: [');
  for (const s of canon.strings) {
    lines.push('    { from: ' + s.from + ', to: ' + s.to +
      ', arc: ' + (s.arc ? 'true' : 'false') +
      ', color: ' + JSON.stringify(s.color) + ' },');
  }
  lines.push('  ],');
  lines.push('  phaseAdvance: ' + canon.phaseAdvance);
  lines.push('};');
  lines.push('export default glyph;');
  return lines.join('\n');
}

// -- geometry -------------------------------------------------------------

const SVG_NS = 'http://www.w3.org/2000/svg';
const CX = 200, CY = 200, R = 150, TICK_R = 14;

function tickPos(t) {
  const a = (-Math.PI / 2) + (t * Math.PI / 6);
  return { x: CX + Math.cos(a) * R, y: CY + Math.sin(a) * R };
}
function el(tag, attrs, children) {
  const n = document.createElementNS(SVG_NS, tag);
  if (attrs) for (const k of Object.keys(attrs)) n.setAttribute(k, attrs[k]);
  if (children) for (const c of children) n.appendChild(c);
  return n;
}
function colorHex(code) {
  return { R: '#ff3b3b', G: '#39ff7a', B: '#3bb6ff', C: '#3bf0ff', M: '#ff3bd0', Y: '#ffe53b' }[code] || '#888';
}

// -- IDE class ------------------------------------------------------------

export class CanonIDE {
  constructor(root) {
    this.root = root;
    this.state = blankCanon('untitled');
    this.tool = 'tick';       // 'tick' | 'string' | 'erase'
    this.color = null;        // selected color
    this.focus = 0;           // keyboard focus index
    this.stringStart = null;  // null when not mid-chord
    this.undoStack = [];
    this.render();
  }

  // -- state mutation ----------------------------------------------------
  setState(next, pushUndo = true) {
    if (pushUndo) this.undoStack.push(JSON.stringify(this.state));
    if (this.undoStack.length > 50) this.undoStack.shift();
    this.state = next;
    this.refresh();
  }
  undo() {
    const prev = this.undoStack.pop();
    if (prev) { this.state = JSON.parse(prev); this.refresh(); }
  }
  loadTemplate(id) {
    const t = getTemplate(id);
    this.setState(t);
    this.announce('Loaded template: ' + id);
  }
  loadBlank() {
    this.setState(blankCanon('untitled'));
    this.announce('Blank canvas');
  }

  // -- editing ops -------------------------------------------------------
  toggleTick(idx) {
    const next = JSON.parse(JSON.stringify(this.state));
    const i = next.ticks.findIndex((t) => t.tick === idx);
    if (i >= 0) {
      next.ticks.splice(i, 1);
      this.announce('Removed tick ' + idx);
    } else {
      next.ticks.push({ tick: idx, color: this.color });
      this.announce('Added tick ' + idx + (this.color ? ' color ' + this.color : ''));
    }
    this.setState(next);
  }
  recolorTickAt(idx) {
    const next = JSON.parse(JSON.stringify(this.state));
    const t = next.ticks.find((x) => x.tick === idx);
    if (t) { t.color = this.color; this.setState(next); }
  }
  addString(from, to) {
    if (from === to) return;
    const next = JSON.parse(JSON.stringify(this.state));
    next.strings.push({ from, to, arc: false, color: this.color });
    this.setState(next);
    this.announce('Added string ' + from + '→' + to);
  }
  removeStringAt(idx) {
    const next = JSON.parse(JSON.stringify(this.state));
    next.strings.splice(idx, 1);
    this.setState(next);
  }

  // -- accessibility live region -----------------------------------------
  announce(msg) {
    const live = this.root.querySelector('.live');
    if (live) live.textContent = msg;
  }

  // -- render ------------------------------------------------------------
  render() {
    this.root.innerHTML = `
      <div class="ide">
        <header class="ide__bar">
          <div class="title">円環 Canon IDE</div>
          <span class="muted">12 ticks · RGBCMY · ESM export</span>
          <label class="muted" for="tplSel">template</label>
          <select id="tplSel">
            <option value="">— blank —</option>
            ${TEMPLATE_IDS.map((id) => `<option value="${id}">${id}</option>`).join('')}
          </select>
          <button id="undoBtn" title="Undo (Cmd+Z)">undo</button>
          <span class="sr-only live" aria-live="polite"></span>
        </header>
        <main class="ide__canvas">
          <svg class="clock" viewBox="0 0 400 400" aria-label="canon editor" tabindex="0">
            <g class="g-rings"></g>
            <g class="g-strings"></g>
            <g class="g-slots"></g>
            <g class="g-ticks"></g>
            <g class="g-labels"></g>
            <g class="g-arrow"></g>
          </svg>
        </main>
        <aside class="ide__panel" aria-label="canon properties">
          <div class="panel__section">
            <h2>metadata</h2>
            <div class="row"><label for="f-id">id</label><input id="f-id" type="text"></div>
            <div class="row"><label for="f-dir">direction</label>
              <select id="f-dir"><option>cw</option><option>ccw</option></select>
            </div>
            <div class="row"><label for="f-dr">doubleRing</label>
              <input id="f-dr" type="checkbox">
            </div>
            <div class="row"><label for="f-pa">phaseAdvance</label>
              <input id="f-pa" type="number" min="-6" max="6" step="1">
            </div>
          </div>
          <div class="panel__section">
            <h2>color</h2>
            <div class="swatches" role="radiogroup" aria-label="active color">
              ${['none','R','G','B','C','M','Y'].map((c) =>
                `<button class="swatch" data-color="${c}" role="radio" aria-checked="false" aria-label="color ${c}"></button>`
              ).join('')}
            </div>
            <h2 style="margin-top:10px">tool</h2>
            <div class="tools">
              <button data-tool="tick">tick</button>
              <button data-tool="string">string</button>
              <button data-tool="erase">erase</button>
            </div>
          </div>
          <div class="panel__section">
            <h2>audio preview</h2>
            <div class="audio-controls">
              <button id="playBtn">▶ play register</button>
              <select id="regSel">
                <option>whisper</option><option>hover</option>
                <option>click</option><option>summon</option><option>revelation</option>
              </select>
            </div>
          </div>
          <div class="panel__section" style="flex:1; overflow:auto">
            <h2>export</h2>
            <pre class="export" aria-label="exported module"></pre>
            <ul class="errors" aria-live="polite"></ul>
            <div class="export-actions">
              <button id="copyBtn">copy</button>
              <button id="dlBtn">download .js</button>
            </div>
          </div>
        </aside>
      </div>`;

    this.bind();
    this.refresh();
  }

  bind() {
    const $ = (sel) => this.root.querySelector(sel);
    $('#tplSel').addEventListener('change', (e) => {
      if (e.target.value) this.loadTemplate(e.target.value);
      else this.loadBlank();
      e.target.value = '';
    });
    $('#undoBtn').addEventListener('click', () => this.undo());
    $('#f-id').addEventListener('input', (e) => {
      const next = { ...this.state, canon: e.target.value };
      this.setState(next, false);
    });
    $('#f-dir').addEventListener('change', (e) => {
      this.setState({ ...this.state, direction: e.target.value });
    });
    $('#f-dr').addEventListener('change', (e) => {
      this.setState({ ...this.state, doubleRing: !!e.target.checked });
    });
    $('#f-pa').addEventListener('input', (e) => {
      const v = parseInt(e.target.value, 10);
      this.setState({ ...this.state, phaseAdvance: Number.isFinite(v) ? v : 0 }, false);
    });

    this.root.querySelectorAll('.swatch').forEach((btn) => {
      btn.addEventListener('click', () => {
        const c = btn.dataset.color;
        this.color = c === 'none' ? null : c;
        this.root.querySelectorAll('.swatch').forEach((b) => {
          b.classList.toggle('active', b === btn);
          b.setAttribute('aria-checked', b === btn ? 'true' : 'false');
        });
      });
    });
    this.root.querySelectorAll('[data-tool]').forEach((btn) => {
      btn.addEventListener('click', () => {
        this.tool = btn.dataset.tool;
        this.stringStart = null;
        this.root.querySelectorAll('[data-tool]').forEach((b) => {
          b.classList.toggle('active', b === btn);
        });
      });
    });

    $('#copyBtn').addEventListener('click', () => this.copyExport());
    $('#dlBtn').addEventListener('click', () => this.download());
    $('#playBtn').addEventListener('click', () => this.preview());

    // keyboard
    this.root.querySelector('.clock').addEventListener('keydown', (e) => this.onKey(e));
    document.addEventListener('keydown', (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'z') { e.preventDefault(); this.undo(); }
    });
  }

  onKey(e) {
    const key = e.key;
    // hex-style toggle: 0..9 a b
    const map = { '0':0,'1':1,'2':2,'3':3,'4':4,'5':5,'6':6,'7':7,'8':8,'9':9,'a':10,'A':10,'b':11,'B':11 };
    if (key in map) {
      e.preventDefault();
      const idx = map[key];
      if (this.tool === 'string') {
        if (this.stringStart == null) { this.stringStart = idx; this.announce('string start ' + idx); }
        else { this.addString(this.stringStart, idx); this.stringStart = null; }
      } else if (this.tool === 'erase') {
        this.toggleTick(idx); // toggling off counts as erase
      } else {
        this.toggleTick(idx);
      }
      return;
    }
    if (key === 'ArrowRight') { this.focus = (this.focus + 1) % 12; this.refresh(); e.preventDefault(); }
    if (key === 'ArrowLeft')  { this.focus = (this.focus + 11) % 12; this.refresh(); e.preventDefault(); }
    if (key === 'Enter') {
      if (this.tool === 'string') {
        if (this.stringStart == null) { this.stringStart = this.focus; this.announce('string start ' + this.focus); }
        else { this.addString(this.stringStart, this.focus); this.stringStart = null; }
      } else {
        this.toggleTick(this.focus);
      }
      e.preventDefault();
    }
    if (key === 'Backspace' || key === 'Delete') {
      // remove tick or string at focus
      const i = this.state.ticks.findIndex((t) => t.tick === this.focus);
      if (i >= 0) this.toggleTick(this.focus);
      e.preventDefault();
    }
  }

  // -- redraw ------------------------------------------------------------
  refresh() {
    const $ = (s) => this.root.querySelector(s);
    $('#f-id').value = this.state.canon;
    $('#f-dir').value = this.state.direction;
    $('#f-dr').checked = !!this.state.doubleRing;
    $('#f-pa').value = String(this.state.phaseAdvance);

    const svg = this.root.querySelector('.clock');
    const gRings = svg.querySelector('.g-rings');
    const gSlots = svg.querySelector('.g-slots');
    const gTicks = svg.querySelector('.g-ticks');
    const gStrings = svg.querySelector('.g-strings');
    const gLabels = svg.querySelector('.g-labels');
    const gArrow = svg.querySelector('.g-arrow');
    [gRings, gSlots, gTicks, gStrings, gLabels, gArrow].forEach((g) => { while (g.firstChild) g.removeChild(g.firstChild); });

    // ring(s)
    gRings.appendChild(el('circle', { cx: CX, cy: CY, r: R, class: 'ring' }));
    if (this.state.doubleRing) {
      gRings.appendChild(el('circle', { cx: CX, cy: CY, r: R - 8, class: 'ring ring--double' }));
    }

    // direction arrow
    const arrow = el('text', { x: CX, y: CY + 6, class: 'direction-arrow', 'text-anchor': 'middle', 'font-size': 18 });
    arrow.textContent = this.state.direction === 'cw' ? '↻' : '↺';
    gArrow.appendChild(arrow);

    // slots + labels + focus halo
    for (let t = 0; t < 12; t++) {
      const p = tickPos(t);
      const slot = el('circle', { cx: p.x, cy: p.y, r: TICK_R, class: 'tick-slot' + (t === this.focus ? ' focused' : '') });
      slot.dataset.tick = String(t);
      slot.addEventListener('click', (ev) => this.onSlotClick(ev, t));
      slot.addEventListener('contextmenu', (ev) => { ev.preventDefault(); this.toggleTick(t); });
      gSlots.appendChild(slot);
      const label = el('text', { x: p.x, y: p.y + (p.y < CY ? -TICK_R - 4 : TICK_R + 12), class: 'label' });
      label.textContent = t.toString(16);
      gLabels.appendChild(label);
    }

    // ticks
    for (const t of this.state.ticks) {
      const p = tickPos(t.tick);
      const dot = el('circle', {
        cx: p.x, cy: p.y, r: TICK_R - 4,
        fill: t.color ? colorHex(t.color) : '#cfcfcf',
        class: 'tick'
      });
      dot.addEventListener('click', (ev) => {
        ev.stopPropagation();
        if (this.tool === 'erase' || ev.altKey) this.toggleTick(t.tick);
        else if (ev.shiftKey) this.recolorTickAt(t.tick);
        else this.onSlotClick(ev, t.tick);
      });
      gTicks.appendChild(dot);
    }

    // strings
    this.state.strings.forEach((s, idx) => {
      const a = tickPos(s.from), b = tickPos(s.to);
      let d;
      if (s.arc) {
        // outer arc bulge
        const mx = (a.x + b.x) / 2, my = (a.y + b.y) / 2;
        const dx = mx - CX, dy = my - CY;
        const len = Math.hypot(dx, dy) || 1;
        const ox = mx + (dx / len) * 60, oy = my + (dy / len) * 60;
        d = `M ${a.x} ${a.y} Q ${ox} ${oy} ${b.x} ${b.y}`;
      } else {
        d = `M ${a.x} ${a.y} L ${b.x} ${b.y}`;
      }
      const path = el('path', { d, class: 'string', stroke: s.color ? colorHex(s.color) : '#cfcfcf' });
      path.addEventListener('click', (ev) => {
        ev.stopPropagation();
        if (this.tool === 'erase' || ev.altKey) this.removeStringAt(idx);
      });
      gStrings.appendChild(path);
    });

    // export panel
    const errs = validate(this.state);
    const pre = this.root.querySelector('pre.export');
    const errList = this.root.querySelector('.errors');
    pre.textContent = exportSource(this.state);
    errList.innerHTML = errs.map((m) => `<li>${m}</li>`).join('');
  }

  onSlotClick(ev, idx) {
    if (this.tool === 'tick') {
      this.toggleTick(idx);
    } else if (this.tool === 'string') {
      if (this.stringStart == null) {
        this.stringStart = idx;
        this.announce('string start ' + idx);
      } else {
        this.addString(this.stringStart, idx);
        this.stringStart = null;
      }
    } else if (this.tool === 'erase') {
      const has = this.state.ticks.some((t) => t.tick === idx);
      if (has) this.toggleTick(idx);
    }
    this.focus = idx;
  }

  // -- export actions ----------------------------------------------------
  copyExport() {
    const errs = validate(this.state);
    if (errs.length) { this.announce('Cannot copy: ' + errs.length + ' error(s)'); return; }
    const src = exportSource(this.state);
    if (navigator.clipboard) navigator.clipboard.writeText(src);
    this.announce('Copied to clipboard');
  }
  download() {
    const errs = validate(this.state);
    if (errs.length) { this.announce('Cannot download: ' + errs.length + ' error(s)'); return; }
    const src = exportSource(this.state);
    const blob = new Blob([src], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = this.state.canon + '.js';
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    this.announce('Downloaded ' + this.state.canon + '.js');
  }

  // -- audio preview -----------------------------------------------------
  preview() {
    const reg = this.root.querySelector('#regSel').value;
    // Prefer cosmos-audio if host injected it
    const api = (typeof window !== 'undefined') && window.__cosmosAudio;
    if (api && typeof api.play === 'function') {
      try { api.play(reg); this.announce('Played ' + reg + ' (cosmos-audio)'); return; } catch (_) {}
    }
    // Fallback: short WebAudio beep
    try {
      const ctx = new (window.AudioContext || window.webkitAudioContext)();
      const o = ctx.createOscillator(); const g = ctx.createGain();
      o.type = 'sine';
      o.frequency.value = { whisper: 220, hover: 330, click: 440, summon: 550, revelation: 660 }[reg] || 440;
      g.gain.value = 0.08;
      o.connect(g).connect(ctx.destination);
      o.start(); o.stop(ctx.currentTime + 0.18);
      o.onended = () => ctx.close();
      this.announce('Played ' + reg + ' (fallback)');
    } catch (_) {
      this.announce('Audio unavailable');
    }
  }
}

export function mount(rootSel) {
  const root = typeof rootSel === 'string' ? document.querySelector(rootSel) : rootSel;
  if (!root) throw new Error('mount root not found');
  return new CanonIDE(root);
}

export default { mount, CanonIDE, validate, exportSource };
