#!/usr/bin/env node
// generate-sitemap.mjs — inryokü sitemap auto-generator
// Extracts PRODUCTS from p3_code_for_claude.js by regex (no eval).
// Backs up existing sitemap.xml before overwriting.

import { readFileSync, writeFileSync, existsSync, copyFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SITE = 'https://inryoku.com';

const STATIC_PAGES = [
    { loc: '/',                priority: '1.0', changefreq: 'daily'   },
    { loc: '/p3_test.html',    priority: '0.9', changefreq: 'daily'   },
    { loc: '/legal.html',      priority: '0.4', changefreq: 'yearly'  },
    { loc: '/privacy.html',    priority: '0.4', changefreq: 'yearly'  },
    { loc: '/returns.html',    priority: '0.4', changefreq: 'yearly'  },
    { loc: '/size-guide.html', priority: '0.5', changefreq: 'monthly' },
];

export function extractProducts(source) {
    // Locate `const PRODUCTS = [ ... ];` block.
    const startMatch = source.match(/const\s+PRODUCTS\s*=\s*\[/);
    if (!startMatch) throw new Error('PRODUCTS array not found');
    let i = startMatch.index + startMatch[0].length - 1; // at '['
    let depth = 0;
    let end = -1;
    for (; i < source.length; i++) {
        const c = source[i];
        if (c === '[') depth++;
        else if (c === ']') {
            depth--;
            if (depth === 0) { end = i; break; }
        }
    }
    if (end < 0) throw new Error('PRODUCTS array unterminated');
    const block = source.slice(startMatch.index, end + 1);

    // Walk block to extract each top-level object body (depth==1 at '{').
    const products = [];
    let bd = 0;          // bracket depth ('[' / ']')
    let braceDepth = 0;  // '{' / '}'
    let objStart = -1;
    for (let j = 0; j < block.length; j++) {
        const c = block[j];
        if (c === '[') bd++;
        else if (c === ']') bd--;
        else if (c === '{') {
            if (bd === 1 && braceDepth === 0) objStart = j + 1;
            braceDepth++;
        } else if (c === '}') {
            braceDepth--;
            if (bd === 1 && braceDepth === 0 && objStart >= 0) {
                const body = block.slice(objStart, j);
                const idM = body.match(/\bid:\s*['"]([^'"]+)['"]/);
                const nameM = body.match(/\bname:\s*['"]([^'"]+)['"]/);
                const imgM = body.match(/\bimage:\s*['"]([^'"]+)['"]/);
                if (idM && nameM && imgM) {
                    products.push({ slug: idM[1], title: nameM[1], image: imgM[1] });
                }
                objStart = -1;
            }
        }
    }
    if (products.length === 0) throw new Error('no products parsed');
    return products;
}

export function getLastmod() {
    try {
        const out = execSync('git log -1 --format=%cI', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] });
        return out.toString().trim().slice(0, 10);
    } catch {
        return new Date().toISOString().slice(0, 10);
    }
}

function xmlEscape(s) {
    return String(s)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

export function buildSitemap(products, lastmod) {
    const lines = [];
    lines.push('<?xml version="1.0" encoding="UTF-8"?>');
    lines.push('<!-- Auto-generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->');
    lines.push('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"');
    lines.push('        xmlns:image="http://www.google.com/schemas/sitemaps/image/1.1"');
    lines.push('        xmlns:xhtml="http://www.w3.org/1999/xhtml">');

    for (const p of STATIC_PAGES) {
        lines.push('  <url>');
        lines.push(`    <loc>${SITE}${p.loc}</loc>`);
        lines.push(`    <lastmod>${lastmod}</lastmod>`);
        lines.push(`    <changefreq>${p.changefreq}</changefreq>`);
        lines.push(`    <priority>${p.priority}</priority>`);
        lines.push(`    <xhtml:link rel="alternate" hreflang="ja" href="${SITE}${p.loc}" />`);
        lines.push(`    <xhtml:link rel="alternate" hreflang="en" href="${SITE}${p.loc}?lang=en" />`);
        lines.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${p.loc}" />`);
        lines.push('  </url>');
    }

    for (const prod of products) {
        const url = `${SITE}/?product=${encodeURIComponent(prod.slug)}`;
        const enUrl = `${SITE}/?product=${encodeURIComponent(prod.slug)}&amp;lang=en`;
        lines.push('  <url>');
        lines.push(`    <loc>${url}</loc>`);
        lines.push(`    <lastmod>${lastmod}</lastmod>`);
        lines.push('    <changefreq>weekly</changefreq>');
        lines.push('    <priority>0.7</priority>');
        lines.push(`    <xhtml:link rel="alternate" hreflang="ja" href="${url}" />`);
        lines.push(`    <xhtml:link rel="alternate" hreflang="en" href="${enUrl}" />`);
        lines.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${url}" />`);
        lines.push('    <image:image>');
        lines.push(`      <image:loc>${SITE}/${prod.image}</image:loc>`);
        lines.push(`      <image:title>${xmlEscape(prod.title)}</image:title>`);
        lines.push('    </image:image>');
        lines.push('  </url>');
    }

    lines.push('</urlset>');
    lines.push('');
    return lines.join('\n');
}

export function run({ root = ROOT, write = true } = {}) {
    const src = readFileSync(resolve(root, 'p3_code_for_claude.js'), 'utf8');
    const products = extractProducts(src);
    const lastmod = getLastmod();
    const xml = buildSitemap(products, lastmod);

    if (write) {
        const target = resolve(root, 'sitemap.xml');
        if (existsSync(target)) {
            const ts = new Date().toISOString().replace(/[:.]/g, '-');
            copyFileSync(target, `${target}.bak-${ts}`);
        }
        writeFileSync(target, xml, 'utf8');
    }
    return { products, lastmod, xml };
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
    const { products, lastmod } = run();
    console.log(`[generate-sitemap] wrote sitemap.xml (${products.length} products, lastmod=${lastmod})`);
}
